version: '3.1'


services:
  db:
    image: postgres:13.1
    privileged: true
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: db
  backend:
    build: ./todo
    privileged: true
    ports:
      - 8080:8080
    command:
      bash -c "python3 manage.py migrate &&
      python3 manage.py fill_db &&
      gunicorn todo.wsgi -b 0.0.0.0:8080"
#      python3 manage.py runserver 0.0.0.0:8080"
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - backend
  frontend:
    build: ./frontend
    ports:
      - 80:80
    depends_on:
      - nginx


#  adminer:
#    image: adminer:4.7.8-standalone
#    restart: always
#    ports:
#      - 8080:8080
#    depends_on:
#      - db